New predict page
vanvalenlab/intro-to-deepcell pull request #38
Opened 2021-05-26 21:34 UTC by ngreenwald

This PR updates the docs to reflect the new functionality that has been added to the predict page, as well as integration with DCL viewer

2021-05-26 22:03 UTC, willgraf approved these changes

2021-05-26 22:03 UTC, willgraf commented
Will this PR be updated with new screenshots as well?

2021-05-26 22:46 UTC, willgraf approved these changes

2021-05-30 18:01 UTC, MekWarrior requested changes
As presently constructed, this addresses parts of #36 but does not close it.
We should explain order of the results (which channel is what and what values they should expect) at minimum. It would also be helpful (but not required since its on model card) to call out resolution again in the data format section.

2021-05-30 23:10 UTC, ngreenwald commented
It was getting kind of wordy so I tried to split it up into categories, ideally ones that would be general enough that they will also apply to the other models once those are ready to go. Let me know what you think

2021-06-01 16:42 UTC, MekWarrior approved these changes
Great changes. Everything reads much better now. 
I have suggested 2 small changes that I'd like to see but they're not worth blocking the merge over.

2021-06-01 16:42 UTC, MekWarrior commented on pretrained_models/README.md
> +Note: The DeepCell.org predict page allows users to specify which channel is the nuclear channel and which is the membrane channel, thus supporting data that is not properly formatted. However, all o
This is great, much cleaner. My only remain suggestion would be to switch the link from 'Running pre-trained models in the cloud' to 'Generating predictions with ImageJ'

2021-06-01 16:42 UTC, MekWarrior commented on pretrained_models/README.md
> +4. Once complete, you can either press Download to view the segmentations locally, or press View to open DeepCell Label to view them interactively.
no comma before 'or'

2021-06-01 17:05 UTC, ngreenwald commented
Great, thanks! Will one of you merge it in?

2021-06-01 18:13 UTC, merged